/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package flann;

public final class flann_log_level_t {
  public final static flann_log_level_t FLANN_LOG_NONE = new flann_log_level_t("FLANN_LOG_NONE", java_flannJNI.FLANN_LOG_NONE_get());
  public final static flann_log_level_t FLANN_LOG_FATAL = new flann_log_level_t("FLANN_LOG_FATAL", java_flannJNI.FLANN_LOG_FATAL_get());
  public final static flann_log_level_t FLANN_LOG_ERROR = new flann_log_level_t("FLANN_LOG_ERROR", java_flannJNI.FLANN_LOG_ERROR_get());
  public final static flann_log_level_t FLANN_LOG_WARN = new flann_log_level_t("FLANN_LOG_WARN", java_flannJNI.FLANN_LOG_WARN_get());
  public final static flann_log_level_t FLANN_LOG_INFO = new flann_log_level_t("FLANN_LOG_INFO", java_flannJNI.FLANN_LOG_INFO_get());
  public final static flann_log_level_t FLANN_LOG_DEBUG = new flann_log_level_t("FLANN_LOG_DEBUG", java_flannJNI.FLANN_LOG_DEBUG_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static flann_log_level_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + flann_log_level_t.class + " with value " + swigValue);
  }

  private flann_log_level_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private flann_log_level_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private flann_log_level_t(String swigName, flann_log_level_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static flann_log_level_t[] swigValues = { FLANN_LOG_NONE, FLANN_LOG_FATAL, FLANN_LOG_ERROR, FLANN_LOG_WARN, FLANN_LOG_INFO, FLANN_LOG_DEBUG };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

