/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package flann;

public final class flann_checks_t {
  public final static flann_checks_t FLANN_CHECKS_UNLIMITED = new flann_checks_t("FLANN_CHECKS_UNLIMITED", java_flannJNI.FLANN_CHECKS_UNLIMITED_get());
  public final static flann_checks_t FLANN_CHECKS_AUTOTUNED = new flann_checks_t("FLANN_CHECKS_AUTOTUNED", java_flannJNI.FLANN_CHECKS_AUTOTUNED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static flann_checks_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + flann_checks_t.class + " with value " + swigValue);
  }

  private flann_checks_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private flann_checks_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private flann_checks_t(String swigName, flann_checks_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static flann_checks_t[] swigValues = { FLANN_CHECKS_UNLIMITED, FLANN_CHECKS_AUTOTUNED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

