/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package flann;

public class FLANNParameters {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FLANNParameters(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FLANNParameters obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        java_flannJNI.delete_FLANNParameters(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAlgorithm(flann_algorithm_t value) {
    java_flannJNI.FLANNParameters_algorithm_set(swigCPtr, this, value.swigValue());
  }

  public flann_algorithm_t getAlgorithm() {
    return flann_algorithm_t.swigToEnum(java_flannJNI.FLANNParameters_algorithm_get(swigCPtr, this));
  }

  public void setChecks(int value) {
    java_flannJNI.FLANNParameters_checks_set(swigCPtr, this, value);
  }

  public int getChecks() {
    return java_flannJNI.FLANNParameters_checks_get(swigCPtr, this);
  }

  public void setEps(float value) {
    java_flannJNI.FLANNParameters_eps_set(swigCPtr, this, value);
  }

  public float getEps() {
    return java_flannJNI.FLANNParameters_eps_get(swigCPtr, this);
  }

  public void setSorted(int value) {
    java_flannJNI.FLANNParameters_sorted_set(swigCPtr, this, value);
  }

  public int getSorted() {
    return java_flannJNI.FLANNParameters_sorted_get(swigCPtr, this);
  }

  public void setMax_neighbors(int value) {
    java_flannJNI.FLANNParameters_max_neighbors_set(swigCPtr, this, value);
  }

  public int getMax_neighbors() {
    return java_flannJNI.FLANNParameters_max_neighbors_get(swigCPtr, this);
  }

  public void setCores(int value) {
    java_flannJNI.FLANNParameters_cores_set(swigCPtr, this, value);
  }

  public int getCores() {
    return java_flannJNI.FLANNParameters_cores_get(swigCPtr, this);
  }

  public void setTrees(int value) {
    java_flannJNI.FLANNParameters_trees_set(swigCPtr, this, value);
  }

  public int getTrees() {
    return java_flannJNI.FLANNParameters_trees_get(swigCPtr, this);
  }

  public void setLeaf_max_size(int value) {
    java_flannJNI.FLANNParameters_leaf_max_size_set(swigCPtr, this, value);
  }

  public int getLeaf_max_size() {
    return java_flannJNI.FLANNParameters_leaf_max_size_get(swigCPtr, this);
  }

  public void setBranching(int value) {
    java_flannJNI.FLANNParameters_branching_set(swigCPtr, this, value);
  }

  public int getBranching() {
    return java_flannJNI.FLANNParameters_branching_get(swigCPtr, this);
  }

  public void setIterations(int value) {
    java_flannJNI.FLANNParameters_iterations_set(swigCPtr, this, value);
  }

  public int getIterations() {
    return java_flannJNI.FLANNParameters_iterations_get(swigCPtr, this);
  }

  public void setCenters_init(flann_centers_init_t value) {
    java_flannJNI.FLANNParameters_centers_init_set(swigCPtr, this, value.swigValue());
  }

  public flann_centers_init_t getCenters_init() {
    return flann_centers_init_t.swigToEnum(java_flannJNI.FLANNParameters_centers_init_get(swigCPtr, this));
  }

  public void setCb_index(float value) {
    java_flannJNI.FLANNParameters_cb_index_set(swigCPtr, this, value);
  }

  public float getCb_index() {
    return java_flannJNI.FLANNParameters_cb_index_get(swigCPtr, this);
  }

  public void setTarget_precision(float value) {
    java_flannJNI.FLANNParameters_target_precision_set(swigCPtr, this, value);
  }

  public float getTarget_precision() {
    return java_flannJNI.FLANNParameters_target_precision_get(swigCPtr, this);
  }

  public void setBuild_weight(float value) {
    java_flannJNI.FLANNParameters_build_weight_set(swigCPtr, this, value);
  }

  public float getBuild_weight() {
    return java_flannJNI.FLANNParameters_build_weight_get(swigCPtr, this);
  }

  public void setMemory_weight(float value) {
    java_flannJNI.FLANNParameters_memory_weight_set(swigCPtr, this, value);
  }

  public float getMemory_weight() {
    return java_flannJNI.FLANNParameters_memory_weight_get(swigCPtr, this);
  }

  public void setSample_fraction(float value) {
    java_flannJNI.FLANNParameters_sample_fraction_set(swigCPtr, this, value);
  }

  public float getSample_fraction() {
    return java_flannJNI.FLANNParameters_sample_fraction_get(swigCPtr, this);
  }

  public void setTable_number_(long value) {
    java_flannJNI.FLANNParameters_table_number__set(swigCPtr, this, value);
  }

  public long getTable_number_() {
    return java_flannJNI.FLANNParameters_table_number__get(swigCPtr, this);
  }

  public void setKey_size_(long value) {
    java_flannJNI.FLANNParameters_key_size__set(swigCPtr, this, value);
  }

  public long getKey_size_() {
    return java_flannJNI.FLANNParameters_key_size__get(swigCPtr, this);
  }

  public void setMulti_probe_level_(long value) {
    java_flannJNI.FLANNParameters_multi_probe_level__set(swigCPtr, this, value);
  }

  public long getMulti_probe_level_() {
    return java_flannJNI.FLANNParameters_multi_probe_level__get(swigCPtr, this);
  }

  public void setLog_level(flann_log_level_t value) {
    java_flannJNI.FLANNParameters_log_level_set(swigCPtr, this, value.swigValue());
  }

  public flann_log_level_t getLog_level() {
    return flann_log_level_t.swigToEnum(java_flannJNI.FLANNParameters_log_level_get(swigCPtr, this));
  }

  public void setRandom_seed(int value) {
    java_flannJNI.FLANNParameters_random_seed_set(swigCPtr, this, value);
  }

  public int getRandom_seed() {
    return java_flannJNI.FLANNParameters_random_seed_get(swigCPtr, this);
  }

  public FLANNParameters() {
    this(java_flannJNI.new_FLANNParameters(), true);
  }

}
