/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package flann;

public final class flann_centers_init_t {
  public final static flann_centers_init_t FLANN_CENTERS_RANDOM = new flann_centers_init_t("FLANN_CENTERS_RANDOM", java_flannJNI.FLANN_CENTERS_RANDOM_get());
  public final static flann_centers_init_t FLANN_CENTERS_GONZALES = new flann_centers_init_t("FLANN_CENTERS_GONZALES", java_flannJNI.FLANN_CENTERS_GONZALES_get());
  public final static flann_centers_init_t FLANN_CENTERS_KMEANSPP = new flann_centers_init_t("FLANN_CENTERS_KMEANSPP", java_flannJNI.FLANN_CENTERS_KMEANSPP_get());
  public final static flann_centers_init_t FLANN_CENTERS_GROUPWISE = new flann_centers_init_t("FLANN_CENTERS_GROUPWISE", java_flannJNI.FLANN_CENTERS_GROUPWISE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static flann_centers_init_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + flann_centers_init_t.class + " with value " + swigValue);
  }

  private flann_centers_init_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private flann_centers_init_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private flann_centers_init_t(String swigName, flann_centers_init_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static flann_centers_init_t[] swigValues = { FLANN_CENTERS_RANDOM, FLANN_CENTERS_GONZALES, FLANN_CENTERS_KMEANSPP, FLANN_CENTERS_GROUPWISE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

