/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package flann;

public final class flann_datatype_t {
  public final static flann_datatype_t FLANN_NONE = new flann_datatype_t("FLANN_NONE", java_flannJNI.FLANN_NONE_get());
  public final static flann_datatype_t FLANN_INT8 = new flann_datatype_t("FLANN_INT8", java_flannJNI.FLANN_INT8_get());
  public final static flann_datatype_t FLANN_INT16 = new flann_datatype_t("FLANN_INT16", java_flannJNI.FLANN_INT16_get());
  public final static flann_datatype_t FLANN_INT32 = new flann_datatype_t("FLANN_INT32", java_flannJNI.FLANN_INT32_get());
  public final static flann_datatype_t FLANN_INT64 = new flann_datatype_t("FLANN_INT64", java_flannJNI.FLANN_INT64_get());
  public final static flann_datatype_t FLANN_UINT8 = new flann_datatype_t("FLANN_UINT8", java_flannJNI.FLANN_UINT8_get());
  public final static flann_datatype_t FLANN_UINT16 = new flann_datatype_t("FLANN_UINT16", java_flannJNI.FLANN_UINT16_get());
  public final static flann_datatype_t FLANN_UINT32 = new flann_datatype_t("FLANN_UINT32", java_flannJNI.FLANN_UINT32_get());
  public final static flann_datatype_t FLANN_UINT64 = new flann_datatype_t("FLANN_UINT64", java_flannJNI.FLANN_UINT64_get());
  public final static flann_datatype_t FLANN_FLOAT32 = new flann_datatype_t("FLANN_FLOAT32", java_flannJNI.FLANN_FLOAT32_get());
  public final static flann_datatype_t FLANN_FLOAT64 = new flann_datatype_t("FLANN_FLOAT64", java_flannJNI.FLANN_FLOAT64_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static flann_datatype_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + flann_datatype_t.class + " with value " + swigValue);
  }

  private flann_datatype_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private flann_datatype_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private flann_datatype_t(String swigName, flann_datatype_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static flann_datatype_t[] swigValues = { FLANN_NONE, FLANN_INT8, FLANN_INT16, FLANN_INT32, FLANN_INT64, FLANN_UINT8, FLANN_UINT16, FLANN_UINT32, FLANN_UINT64, FLANN_FLOAT32, FLANN_FLOAT64 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

