/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package flann;

public final class flann_distance_t {
  public final static flann_distance_t FLANN_DIST_EUCLIDEAN = new flann_distance_t("FLANN_DIST_EUCLIDEAN", java_flannJNI.FLANN_DIST_EUCLIDEAN_get());
  public final static flann_distance_t FLANN_DIST_L2 = new flann_distance_t("FLANN_DIST_L2", java_flannJNI.FLANN_DIST_L2_get());
  public final static flann_distance_t FLANN_DIST_MANHATTAN = new flann_distance_t("FLANN_DIST_MANHATTAN", java_flannJNI.FLANN_DIST_MANHATTAN_get());
  public final static flann_distance_t FLANN_DIST_L1 = new flann_distance_t("FLANN_DIST_L1", java_flannJNI.FLANN_DIST_L1_get());
  public final static flann_distance_t FLANN_DIST_MINKOWSKI = new flann_distance_t("FLANN_DIST_MINKOWSKI", java_flannJNI.FLANN_DIST_MINKOWSKI_get());
  public final static flann_distance_t FLANN_DIST_MAX = new flann_distance_t("FLANN_DIST_MAX", java_flannJNI.FLANN_DIST_MAX_get());
  public final static flann_distance_t FLANN_DIST_HIST_INTERSECT = new flann_distance_t("FLANN_DIST_HIST_INTERSECT", java_flannJNI.FLANN_DIST_HIST_INTERSECT_get());
  public final static flann_distance_t FLANN_DIST_HELLINGER = new flann_distance_t("FLANN_DIST_HELLINGER", java_flannJNI.FLANN_DIST_HELLINGER_get());
  public final static flann_distance_t FLANN_DIST_CHI_SQUARE = new flann_distance_t("FLANN_DIST_CHI_SQUARE", java_flannJNI.FLANN_DIST_CHI_SQUARE_get());
  public final static flann_distance_t FLANN_DIST_KULLBACK_LEIBLER = new flann_distance_t("FLANN_DIST_KULLBACK_LEIBLER", java_flannJNI.FLANN_DIST_KULLBACK_LEIBLER_get());
  public final static flann_distance_t FLANN_DIST_HAMMING = new flann_distance_t("FLANN_DIST_HAMMING", java_flannJNI.FLANN_DIST_HAMMING_get());
  public final static flann_distance_t FLANN_DIST_HAMMING_LUT = new flann_distance_t("FLANN_DIST_HAMMING_LUT", java_flannJNI.FLANN_DIST_HAMMING_LUT_get());
  public final static flann_distance_t FLANN_DIST_HAMMING_POPCNT = new flann_distance_t("FLANN_DIST_HAMMING_POPCNT", java_flannJNI.FLANN_DIST_HAMMING_POPCNT_get());
  public final static flann_distance_t FLANN_DIST_L2_SIMPLE = new flann_distance_t("FLANN_DIST_L2_SIMPLE", java_flannJNI.FLANN_DIST_L2_SIMPLE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static flann_distance_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + flann_distance_t.class + " with value " + swigValue);
  }

  private flann_distance_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private flann_distance_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private flann_distance_t(String swigName, flann_distance_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static flann_distance_t[] swigValues = { FLANN_DIST_EUCLIDEAN, FLANN_DIST_L2, FLANN_DIST_MANHATTAN, FLANN_DIST_L1, FLANN_DIST_MINKOWSKI, FLANN_DIST_MAX, FLANN_DIST_HIST_INTERSECT, FLANN_DIST_HELLINGER, FLANN_DIST_CHI_SQUARE, FLANN_DIST_KULLBACK_LEIBLER, FLANN_DIST_HAMMING, FLANN_DIST_HAMMING_LUT, FLANN_DIST_HAMMING_POPCNT, FLANN_DIST_L2_SIMPLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

