/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package flann;

public final class flann_algorithm_t {
  public final static flann_algorithm_t FLANN_INDEX_LINEAR = new flann_algorithm_t("FLANN_INDEX_LINEAR", java_flannJNI.FLANN_INDEX_LINEAR_get());
  public final static flann_algorithm_t FLANN_INDEX_KDTREE = new flann_algorithm_t("FLANN_INDEX_KDTREE", java_flannJNI.FLANN_INDEX_KDTREE_get());
  public final static flann_algorithm_t FLANN_INDEX_KMEANS = new flann_algorithm_t("FLANN_INDEX_KMEANS", java_flannJNI.FLANN_INDEX_KMEANS_get());
  public final static flann_algorithm_t FLANN_INDEX_COMPOSITE = new flann_algorithm_t("FLANN_INDEX_COMPOSITE", java_flannJNI.FLANN_INDEX_COMPOSITE_get());
  public final static flann_algorithm_t FLANN_INDEX_KDTREE_SINGLE = new flann_algorithm_t("FLANN_INDEX_KDTREE_SINGLE", java_flannJNI.FLANN_INDEX_KDTREE_SINGLE_get());
  public final static flann_algorithm_t FLANN_INDEX_HIERARCHICAL = new flann_algorithm_t("FLANN_INDEX_HIERARCHICAL", java_flannJNI.FLANN_INDEX_HIERARCHICAL_get());
  public final static flann_algorithm_t FLANN_INDEX_LSH = new flann_algorithm_t("FLANN_INDEX_LSH", java_flannJNI.FLANN_INDEX_LSH_get());
  public final static flann_algorithm_t FLANN_INDEX_SAVED = new flann_algorithm_t("FLANN_INDEX_SAVED", java_flannJNI.FLANN_INDEX_SAVED_get());
  public final static flann_algorithm_t FLANN_INDEX_AUTOTUNED = new flann_algorithm_t("FLANN_INDEX_AUTOTUNED", java_flannJNI.FLANN_INDEX_AUTOTUNED_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static flann_algorithm_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + flann_algorithm_t.class + " with value " + swigValue);
  }

  private flann_algorithm_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private flann_algorithm_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private flann_algorithm_t(String swigName, flann_algorithm_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static flann_algorithm_t[] swigValues = { FLANN_INDEX_LINEAR, FLANN_INDEX_KDTREE, FLANN_INDEX_KMEANS, FLANN_INDEX_COMPOSITE, FLANN_INDEX_KDTREE_SINGLE, FLANN_INDEX_HIERARCHICAL, FLANN_INDEX_LSH, FLANN_INDEX_SAVED, FLANN_INDEX_AUTOTUNED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

