/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "/usr/local/src/flann/src/cpp/flann/defines.h"
#include "/usr/local/src/flann/src/cpp/flann/flann.h"


static double *new_doublep() { 
  return (double *) calloc(1,sizeof(double)); 
}

static double *copy_doublep(double value) { 
  double *obj = (double *) calloc(1,sizeof(double));
  *obj = value;
  return obj; 
}

static void delete_doublep(double *obj) { 
  if (obj) free(obj); 
}

static void doublep_assign(double *obj, double value) {
  *obj = value;
}

static double doublep_value(double *obj) {
  return *obj;
}


static float *new_floatp() { 
  return (float *) calloc(1,sizeof(float)); 
}

static float *copy_floatp(float value) { 
  float *obj = (float *) calloc(1,sizeof(float));
  *obj = value;
  return obj; 
}

static void delete_floatp(float *obj) { 
  if (obj) free(obj); 
}

static void floatp_assign(float *obj, float value) {
  *obj = value;
}

static float floatp_value(float *obj) {
  return *obj;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INDEX_1LINEAR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_algorithm_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_algorithm_t)FLANN_INDEX_LINEAR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INDEX_1KDTREE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_algorithm_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_algorithm_t)FLANN_INDEX_KDTREE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INDEX_1KMEANS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_algorithm_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_algorithm_t)FLANN_INDEX_KMEANS;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INDEX_1COMPOSITE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_algorithm_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_algorithm_t)FLANN_INDEX_COMPOSITE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INDEX_1KDTREE_1SINGLE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_algorithm_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_algorithm_t)FLANN_INDEX_KDTREE_SINGLE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INDEX_1HIERARCHICAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_algorithm_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_algorithm_t)FLANN_INDEX_HIERARCHICAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INDEX_1LSH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_algorithm_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_algorithm_t)FLANN_INDEX_LSH;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INDEX_1SAVED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_algorithm_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_algorithm_t)FLANN_INDEX_SAVED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INDEX_1AUTOTUNED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_algorithm_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_algorithm_t)FLANN_INDEX_AUTOTUNED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1CENTERS_1RANDOM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_centers_init_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_centers_init_t)FLANN_CENTERS_RANDOM;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1CENTERS_1GONZALES_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_centers_init_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_centers_init_t)FLANN_CENTERS_GONZALES;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1CENTERS_1KMEANSPP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_centers_init_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_centers_init_t)FLANN_CENTERS_KMEANSPP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1CENTERS_1GROUPWISE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_centers_init_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_centers_init_t)FLANN_CENTERS_GROUPWISE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1LOG_1NONE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_log_level_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_log_level_t)FLANN_LOG_NONE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1LOG_1FATAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_log_level_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_log_level_t)FLANN_LOG_FATAL;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1LOG_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_log_level_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_log_level_t)FLANN_LOG_ERROR;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1LOG_1WARN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_log_level_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_log_level_t)FLANN_LOG_WARN;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1LOG_1INFO_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_log_level_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_log_level_t)FLANN_LOG_INFO;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1LOG_1DEBUG_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_log_level_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_log_level_t)FLANN_LOG_DEBUG;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1EUCLIDEAN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_EUCLIDEAN;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1L2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_L2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1MANHATTAN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_MANHATTAN;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1L1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_L1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1MINKOWSKI_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_MINKOWSKI;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1MAX_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_MAX;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1HIST_1INTERSECT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_HIST_INTERSECT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1HELLINGER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_HELLINGER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1CHI_1SQUARE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_CHI_SQUARE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1KULLBACK_1LEIBLER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_KULLBACK_LEIBLER;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1HAMMING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_HAMMING;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1HAMMING_1LUT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_HAMMING_LUT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1HAMMING_1POPCNT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_HAMMING_POPCNT;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1DIST_1L2_1SIMPLE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)FLANN_DIST_L2_SIMPLE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1NONE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_NONE;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INT8_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_INT8;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INT16_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_INT16;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INT32_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_INT32;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1INT64_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_INT64;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1UINT8_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_UINT8;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1UINT16_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_UINT16;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1UINT32_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_UINT32;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1UINT64_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_UINT64;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1FLOAT32_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_FLOAT32;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1FLOAT64_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_datatype_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_datatype_t)FLANN_FLOAT64;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1CHECKS_1UNLIMITED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_checks_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_checks_t)FLANN_CHECKS_UNLIMITED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANN_1CHECKS_1AUTOTUNED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_checks_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_checks_t)FLANN_CHECKS_AUTOTUNED;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1algorithm_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  enum flann_algorithm_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (enum flann_algorithm_t)jarg2; 
  if (arg1) (arg1)->algorithm = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1algorithm_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  enum flann_algorithm_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (enum flann_algorithm_t) ((arg1)->algorithm);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1checks_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->checks = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1checks_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (int) ((arg1)->checks);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1eps_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->eps = arg2;
}


SWIGEXPORT jfloat JNICALL Java_flann_java_1flannJNI_FLANNParameters_1eps_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (float) ((arg1)->eps);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1sorted_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->sorted = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1sorted_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (int) ((arg1)->sorted);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1max_1neighbors_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->max_neighbors = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1max_1neighbors_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (int) ((arg1)->max_neighbors);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1cores_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->cores = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1cores_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (int) ((arg1)->cores);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1trees_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->trees = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1trees_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (int) ((arg1)->trees);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1leaf_1max_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->leaf_max_size = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1leaf_1max_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (int) ((arg1)->leaf_max_size);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1branching_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->branching = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1branching_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (int) ((arg1)->branching);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1iterations_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->iterations = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1iterations_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (int) ((arg1)->iterations);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1centers_1init_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  enum flann_centers_init_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (enum flann_centers_init_t)jarg2; 
  if (arg1) (arg1)->centers_init = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1centers_1init_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  enum flann_centers_init_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (enum flann_centers_init_t) ((arg1)->centers_init);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1cb_1index_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->cb_index = arg2;
}


SWIGEXPORT jfloat JNICALL Java_flann_java_1flannJNI_FLANNParameters_1cb_1index_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (float) ((arg1)->cb_index);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1target_1precision_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->target_precision = arg2;
}


SWIGEXPORT jfloat JNICALL Java_flann_java_1flannJNI_FLANNParameters_1target_1precision_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (float) ((arg1)->target_precision);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1build_1weight_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->build_weight = arg2;
}


SWIGEXPORT jfloat JNICALL Java_flann_java_1flannJNI_FLANNParameters_1build_1weight_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (float) ((arg1)->build_weight);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1memory_1weight_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->memory_weight = arg2;
}


SWIGEXPORT jfloat JNICALL Java_flann_java_1flannJNI_FLANNParameters_1memory_1weight_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (float) ((arg1)->memory_weight);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1sample_1fraction_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->sample_fraction = arg2;
}


SWIGEXPORT jfloat JNICALL Java_flann_java_1flannJNI_FLANNParameters_1sample_1fraction_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (float) ((arg1)->sample_fraction);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1table_1number_1_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->table_number_ = arg2;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_FLANNParameters_1table_1number_1_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (unsigned int) ((arg1)->table_number_);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1key_1size_1_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->key_size_ = arg2;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_FLANNParameters_1key_1size_1_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (unsigned int) ((arg1)->key_size_);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1multi_1probe_1level_1_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  unsigned int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  if (arg1) (arg1)->multi_probe_level_ = arg2;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_FLANNParameters_1multi_1probe_1level_1_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (unsigned int) ((arg1)->multi_probe_level_);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1log_1level_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  enum flann_log_level_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (enum flann_log_level_t)jarg2; 
  if (arg1) (arg1)->log_level = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1log_1level_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  enum flann_log_level_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (enum flann_log_level_t) ((arg1)->log_level);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_FLANNParameters_1random_1seed_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  long arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  arg2 = (long)jarg2; 
  if (arg1) (arg1)->random_seed = arg2;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_FLANNParameters_1random_1seed_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  result = (long) ((arg1)->random_seed);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_new_1FLANNParameters(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct FLANNParameters *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct FLANNParameters *)calloc(1, sizeof(struct FLANNParameters));
  *(struct FLANNParameters **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_delete_1FLANNParameters(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_DEFAULT_1FLANN_1PARAMETERS_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct FLANNParameters *arg1 = (struct FLANNParameters *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct FLANNParameters **)&jarg1; 
  DEFAULT_FLANN_PARAMETERS = *arg1;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_DEFAULT_1FLANN_1PARAMETERS_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct FLANNParameters *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct FLANNParameters *)&DEFAULT_FLANN_PARAMETERS;
  *(struct FLANNParameters **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_flann_1log_1verbosity(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  flann_log_verbosity(arg1);
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_flann_1set_1distance_1type(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  enum flann_distance_t arg1 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (enum flann_distance_t)jarg1; 
  arg2 = (int)jarg2; 
  flann_set_distance_type(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1get_1distance_1type(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum flann_distance_t result;
  
  (void)jenv;
  (void)jcls;
  result = (enum flann_distance_t)flann_get_distance_type();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1get_1distance_1order(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)flann_get_distance_order();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1build_1index(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jlong jarg5, jobject jarg5_) {
  jlong jresult = 0 ;
  float *arg1 = (float *) 0 ;
  int arg2 ;
  int arg3 ;
  float *arg4 = (float *) 0 ;
  struct FLANNParameters *arg5 = (struct FLANNParameters *) 0 ;
  flann_index_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  arg1 = *(float **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = *(struct FLANNParameters **)&jarg5; 
  result = (flann_index_t)flann_build_index(arg1,arg2,arg3,arg4,arg5);
  *(flann_index_t *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1build_1index_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jlong jarg5, jobject jarg5_) {
  jlong jresult = 0 ;
  float *arg1 = (float *) 0 ;
  int arg2 ;
  int arg3 ;
  float *arg4 = (float *) 0 ;
  struct FLANNParameters *arg5 = (struct FLANNParameters *) 0 ;
  flann_index_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  arg1 = *(float **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = *(struct FLANNParameters **)&jarg5; 
  result = (flann_index_t)flann_build_index_float(arg1,arg2,arg3,arg4,arg5);
  *(flann_index_t *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1build_1index_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jlong jarg5, jobject jarg5_) {
  jlong jresult = 0 ;
  double *arg1 = (double *) 0 ;
  int arg2 ;
  int arg3 ;
  float *arg4 = (float *) 0 ;
  struct FLANNParameters *arg5 = (struct FLANNParameters *) 0 ;
  flann_index_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  arg1 = *(double **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = *(struct FLANNParameters **)&jarg5; 
  result = (flann_index_t)flann_build_index_double(arg1,arg2,arg3,arg4,arg5);
  *(flann_index_t *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1build_1index_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jlong jarg5, jobject jarg5_) {
  jlong jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  int arg2 ;
  int arg3 ;
  float *arg4 = (float *) 0 ;
  struct FLANNParameters *arg5 = (struct FLANNParameters *) 0 ;
  flann_index_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  arg1 = *(unsigned char **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = *(struct FLANNParameters **)&jarg5; 
  result = (flann_index_t)flann_build_index_byte(arg1,arg2,arg3,arg4,arg5);
  *(flann_index_t *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1build_1index_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jlong jarg5, jobject jarg5_) {
  jlong jresult = 0 ;
  int *arg1 = (int *) 0 ;
  int arg2 ;
  int arg3 ;
  float *arg4 = (float *) 0 ;
  struct FLANNParameters *arg5 = (struct FLANNParameters *) 0 ;
  flann_index_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  arg1 = *(int **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = *(struct FLANNParameters **)&jarg5; 
  result = (flann_index_t)flann_build_index_int(arg1,arg2,arg3,arg4,arg5);
  *(flann_index_t *)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1add_1points(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jfloat jarg5) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  float arg5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(float **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (float)jarg5; 
  result = (int)flann_add_points(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1add_1points_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jfloat jarg5) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  float arg5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(float **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (float)jarg5; 
  result = (int)flann_add_points_float(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1add_1points_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jfloat jarg5) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  int arg4 ;
  float arg5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (float)jarg5; 
  result = (int)flann_add_points_double(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1add_1points_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jfloat jarg5) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  int arg3 ;
  int arg4 ;
  float arg5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (float)jarg5; 
  result = (int)flann_add_points_byte(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1add_1points_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jfloat jarg5) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  int *arg2 = (int *) 0 ;
  int arg3 ;
  int arg4 ;
  float arg5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (float)jarg5; 
  result = (int)flann_add_points_int(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1remove_1point(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int)flann_remove_point(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1remove_1point_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int)flann_remove_point_float(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1remove_1point_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int)flann_remove_point_double(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1remove_1point_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int)flann_remove_point_byte(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1remove_1point_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int)flann_remove_point_int(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1get_1point(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int arg2 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (float *)flann_get_point(arg1,arg2);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1get_1point_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int arg2 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (float *)flann_get_point_float(arg1,arg2);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1get_1point_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int arg2 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (double *)flann_get_point_double(arg1,arg2);
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1get_1point_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int arg2 ;
  unsigned char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (unsigned char *)flann_get_point_byte(arg1,arg2);
  *(unsigned char **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1get_1point_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int arg2 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  result = (int *)flann_get_point_int(arg1,arg2);
  *(int **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1veclen(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (unsigned int)flann_veclen(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1veclen_1float(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (unsigned int)flann_veclen_float(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1veclen_1double(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (unsigned int)flann_veclen_double(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1veclen_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (unsigned int)flann_veclen_byte(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1veclen_1int(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (unsigned int)flann_veclen_int(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1size(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (unsigned int)flann_size(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1size_1float(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (unsigned int)flann_size_float(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1size_1double(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (unsigned int)flann_size_double(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1size_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (unsigned int)flann_size_byte(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1size_1int(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (unsigned int)flann_size_int(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1used_1memory(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (int)flann_used_memory(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1used_1memory_1float(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (int)flann_used_memory_float(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1used_1memory_1double(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (int)flann_used_memory_double(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1used_1memory_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (int)flann_used_memory_byte(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1used_1memory_1int(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  result = (int)flann_used_memory_int(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1save_1index(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)flann_save_index(arg1,arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1save_1index_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)flann_save_index_float(arg1,arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1save_1index_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)flann_save_index_double(arg1,arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1save_1index_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)flann_save_index_byte(arg1,arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1save_1index_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)flann_save_index_int(arg1,arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1load_1index(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  flann_index_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(float **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (flann_index_t)flann_load_index(arg1,arg2,arg3,arg4);
  *(flann_index_t *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1load_1index_1float(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  flann_index_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(float **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (flann_index_t)flann_load_index_float(arg1,arg2,arg3,arg4);
  *(flann_index_t *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1load_1index_1double(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  int arg4 ;
  flann_index_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (flann_index_t)flann_load_index_double(arg1,arg2,arg3,arg4);
  *(flann_index_t *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1load_1index_1byte(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  int arg3 ;
  int arg4 ;
  flann_index_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(unsigned char **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (flann_index_t)flann_load_index_byte(arg1,arg2,arg3,arg4);
  *(flann_index_t *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_flann_1load_1index_1int(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int *arg2 = (int *) 0 ;
  int arg3 ;
  int arg4 ;
  flann_index_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(int **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (flann_index_t)flann_load_index_int(arg1,arg2,arg3,arg4);
  *(flann_index_t *)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1find_1nearest_1neighbors(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7, jint jarg8, jlong jarg9, jobject jarg9_) {
  jint jresult = 0 ;
  float *arg1 = (float *) 0 ;
  int arg2 ;
  int arg3 ;
  float *arg4 = (float *) 0 ;
  int arg5 ;
  int *arg6 = (int *) 0 ;
  float *arg7 = (float *) 0 ;
  int arg8 ;
  struct FLANNParameters *arg9 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg9_;
  arg1 = *(float **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = *(int **)&jarg6; 
  arg7 = *(float **)&jarg7; 
  arg8 = (int)jarg8; 
  arg9 = *(struct FLANNParameters **)&jarg9; 
  result = (int)flann_find_nearest_neighbors(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1find_1nearest_1neighbors_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7, jint jarg8, jlong jarg9, jobject jarg9_) {
  jint jresult = 0 ;
  float *arg1 = (float *) 0 ;
  int arg2 ;
  int arg3 ;
  float *arg4 = (float *) 0 ;
  int arg5 ;
  int *arg6 = (int *) 0 ;
  float *arg7 = (float *) 0 ;
  int arg8 ;
  struct FLANNParameters *arg9 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg9_;
  arg1 = *(float **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = *(int **)&jarg6; 
  arg7 = *(float **)&jarg7; 
  arg8 = (int)jarg8; 
  arg9 = *(struct FLANNParameters **)&jarg9; 
  result = (int)flann_find_nearest_neighbors_float(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1find_1nearest_1neighbors_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7, jint jarg8, jlong jarg9, jobject jarg9_) {
  jint jresult = 0 ;
  double *arg1 = (double *) 0 ;
  int arg2 ;
  int arg3 ;
  double *arg4 = (double *) 0 ;
  int arg5 ;
  int *arg6 = (int *) 0 ;
  double *arg7 = (double *) 0 ;
  int arg8 ;
  struct FLANNParameters *arg9 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg9_;
  arg1 = *(double **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = *(int **)&jarg6; 
  arg7 = *(double **)&jarg7; 
  arg8 = (int)jarg8; 
  arg9 = *(struct FLANNParameters **)&jarg9; 
  result = (int)flann_find_nearest_neighbors_double(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1find_1nearest_1neighbors_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7, jint jarg8, jlong jarg9, jobject jarg9_) {
  jint jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  int arg2 ;
  int arg3 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  int arg5 ;
  int *arg6 = (int *) 0 ;
  float *arg7 = (float *) 0 ;
  int arg8 ;
  struct FLANNParameters *arg9 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg9_;
  arg1 = *(unsigned char **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(unsigned char **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = *(int **)&jarg6; 
  arg7 = *(float **)&jarg7; 
  arg8 = (int)jarg8; 
  arg9 = *(struct FLANNParameters **)&jarg9; 
  result = (int)flann_find_nearest_neighbors_byte(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1find_1nearest_1neighbors_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jlong jarg4, jint jarg5, jlong jarg6, jlong jarg7, jint jarg8, jlong jarg9, jobject jarg9_) {
  jint jresult = 0 ;
  int *arg1 = (int *) 0 ;
  int arg2 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  int arg5 ;
  int *arg6 = (int *) 0 ;
  float *arg7 = (float *) 0 ;
  int arg8 ;
  struct FLANNParameters *arg9 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg9_;
  arg1 = *(int **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(int **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = *(int **)&jarg6; 
  arg7 = *(float **)&jarg7; 
  arg8 = (int)jarg8; 
  arg9 = *(struct FLANNParameters **)&jarg9; 
  result = (int)flann_find_nearest_neighbors_int(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1find_1nearest_1neighbors_1index(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5, jint jarg6, jlong jarg7, jobject jarg7_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  float *arg5 = (float *) 0 ;
  int arg6 ;
  struct FLANNParameters *arg7 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg7_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(float **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(int **)&jarg4; 
  arg5 = *(float **)&jarg5; 
  arg6 = (int)jarg6; 
  arg7 = *(struct FLANNParameters **)&jarg7; 
  result = (int)flann_find_nearest_neighbors_index(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1find_1nearest_1neighbors_1index_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5, jint jarg6, jlong jarg7, jobject jarg7_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  float *arg5 = (float *) 0 ;
  int arg6 ;
  struct FLANNParameters *arg7 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg7_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(float **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(int **)&jarg4; 
  arg5 = *(float **)&jarg5; 
  arg6 = (int)jarg6; 
  arg7 = *(struct FLANNParameters **)&jarg7; 
  result = (int)flann_find_nearest_neighbors_index_float(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1find_1nearest_1neighbors_1index_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5, jint jarg6, jlong jarg7, jobject jarg7_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  double *arg2 = (double *) 0 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  double *arg5 = (double *) 0 ;
  int arg6 ;
  struct FLANNParameters *arg7 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg7_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(int **)&jarg4; 
  arg5 = *(double **)&jarg5; 
  arg6 = (int)jarg6; 
  arg7 = *(struct FLANNParameters **)&jarg7; 
  result = (int)flann_find_nearest_neighbors_index_double(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1find_1nearest_1neighbors_1index_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5, jint jarg6, jlong jarg7, jobject jarg7_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  float *arg5 = (float *) 0 ;
  int arg6 ;
  struct FLANNParameters *arg7 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg7_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(int **)&jarg4; 
  arg5 = *(float **)&jarg5; 
  arg6 = (int)jarg6; 
  arg7 = *(struct FLANNParameters **)&jarg7; 
  result = (int)flann_find_nearest_neighbors_index_byte(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1find_1nearest_1neighbors_1index_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jlong jarg4, jlong jarg5, jint jarg6, jlong jarg7, jobject jarg7_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  int *arg2 = (int *) 0 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  float *arg5 = (float *) 0 ;
  int arg6 ;
  struct FLANNParameters *arg7 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg7_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(int **)&jarg4; 
  arg5 = *(float **)&jarg5; 
  arg6 = (int)jarg6; 
  arg7 = *(struct FLANNParameters **)&jarg7; 
  result = (int)flann_find_nearest_neighbors_index_int(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1radius_1search(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jint jarg5, jfloat jarg6, jlong jarg7, jobject jarg7_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  float *arg2 = (float *) 0 ;
  int *arg3 = (int *) 0 ;
  float *arg4 = (float *) 0 ;
  int arg5 ;
  float arg6 ;
  struct FLANNParameters *arg7 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg7_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(float **)&jarg2; 
  arg3 = *(int **)&jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (float)jarg6; 
  arg7 = *(struct FLANNParameters **)&jarg7; 
  result = (int)flann_radius_search(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1radius_1search_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jint jarg5, jfloat jarg6, jlong jarg7, jobject jarg7_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  float *arg2 = (float *) 0 ;
  int *arg3 = (int *) 0 ;
  float *arg4 = (float *) 0 ;
  int arg5 ;
  float arg6 ;
  struct FLANNParameters *arg7 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg7_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(float **)&jarg2; 
  arg3 = *(int **)&jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (float)jarg6; 
  arg7 = *(struct FLANNParameters **)&jarg7; 
  result = (int)flann_radius_search_float(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1radius_1search_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jint jarg5, jfloat jarg6, jlong jarg7, jobject jarg7_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  double *arg2 = (double *) 0 ;
  int *arg3 = (int *) 0 ;
  double *arg4 = (double *) 0 ;
  int arg5 ;
  float arg6 ;
  struct FLANNParameters *arg7 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg7_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(double **)&jarg2; 
  arg3 = *(int **)&jarg3; 
  arg4 = *(double **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (float)jarg6; 
  arg7 = *(struct FLANNParameters **)&jarg7; 
  result = (int)flann_radius_search_double(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1radius_1search_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jint jarg5, jfloat jarg6, jlong jarg7, jobject jarg7_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  int *arg3 = (int *) 0 ;
  float *arg4 = (float *) 0 ;
  int arg5 ;
  float arg6 ;
  struct FLANNParameters *arg7 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg7_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  arg3 = *(int **)&jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (float)jarg6; 
  arg7 = *(struct FLANNParameters **)&jarg7; 
  result = (int)flann_radius_search_byte(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1radius_1search_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jint jarg5, jfloat jarg6, jlong jarg7, jobject jarg7_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  float *arg4 = (float *) 0 ;
  int arg5 ;
  float arg6 ;
  struct FLANNParameters *arg7 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg7_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = *(int **)&jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (float)jarg6; 
  arg7 = *(struct FLANNParameters **)&jarg7; 
  result = (int)flann_radius_search_int(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1free_1index(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  struct FLANNParameters *arg2 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(struct FLANNParameters **)&jarg2; 
  result = (int)flann_free_index(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1free_1index_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  struct FLANNParameters *arg2 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(struct FLANNParameters **)&jarg2; 
  result = (int)flann_free_index_float(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1free_1index_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  struct FLANNParameters *arg2 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(struct FLANNParameters **)&jarg2; 
  result = (int)flann_free_index_double(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1free_1index_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  struct FLANNParameters *arg2 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(struct FLANNParameters **)&jarg2; 
  result = (int)flann_free_index_byte(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1free_1index_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  flann_index_t arg1 = (flann_index_t) 0 ;
  struct FLANNParameters *arg2 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  arg1 = *(flann_index_t *)&jarg1; 
  arg2 = *(struct FLANNParameters **)&jarg2; 
  result = (int)flann_free_index_int(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1compute_1cluster_1centers(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jint jarg4, jlong jarg5, jlong jarg6, jobject jarg6_) {
  jint jresult = 0 ;
  float *arg1 = (float *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  float *arg5 = (float *) 0 ;
  struct FLANNParameters *arg6 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg6_;
  arg1 = *(float **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(float **)&jarg5; 
  arg6 = *(struct FLANNParameters **)&jarg6; 
  result = (int)flann_compute_cluster_centers(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1compute_1cluster_1centers_1float(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jint jarg4, jlong jarg5, jlong jarg6, jobject jarg6_) {
  jint jresult = 0 ;
  float *arg1 = (float *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  float *arg5 = (float *) 0 ;
  struct FLANNParameters *arg6 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg6_;
  arg1 = *(float **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(float **)&jarg5; 
  arg6 = *(struct FLANNParameters **)&jarg6; 
  result = (int)flann_compute_cluster_centers_float(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1compute_1cluster_1centers_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jint jarg4, jlong jarg5, jlong jarg6, jobject jarg6_) {
  jint jresult = 0 ;
  double *arg1 = (double *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  double *arg5 = (double *) 0 ;
  struct FLANNParameters *arg6 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg6_;
  arg1 = *(double **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(double **)&jarg5; 
  arg6 = *(struct FLANNParameters **)&jarg6; 
  result = (int)flann_compute_cluster_centers_double(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1compute_1cluster_1centers_1byte(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jint jarg4, jlong jarg5, jlong jarg6, jobject jarg6_) {
  jint jresult = 0 ;
  unsigned char *arg1 = (unsigned char *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  float *arg5 = (float *) 0 ;
  struct FLANNParameters *arg6 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg6_;
  arg1 = *(unsigned char **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(float **)&jarg5; 
  arg6 = *(struct FLANNParameters **)&jarg6; 
  result = (int)flann_compute_cluster_centers_byte(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_flann_java_1flannJNI_flann_1compute_1cluster_1centers_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3, jint jarg4, jlong jarg5, jlong jarg6, jobject jarg6_) {
  jint jresult = 0 ;
  int *arg1 = (int *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  float *arg5 = (float *) 0 ;
  struct FLANNParameters *arg6 = (struct FLANNParameters *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg6_;
  arg1 = *(int **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = *(float **)&jarg5; 
  arg6 = *(struct FLANNParameters **)&jarg6; 
  result = (int)flann_compute_cluster_centers_int(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_new_1doublep(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (double *)new_doublep();
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_copy_1doublep(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  jlong jresult = 0 ;
  double arg1 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  result = (double *)copy_doublep(arg1);
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_delete_1doublep(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  double *arg1 = (double *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  delete_doublep(arg1);
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_doublep_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
  double *arg1 = (double *) 0 ;
  double arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  arg2 = (double)jarg2; 
  doublep_assign(arg1,arg2);
}


SWIGEXPORT jdouble JNICALL Java_flann_java_1flannJNI_doublep_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jdouble jresult = 0 ;
  double *arg1 = (double *) 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  result = (double)doublep_value(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_new_1floatp(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (float *)new_floatp();
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_flann_java_1flannJNI_copy_1floatp(JNIEnv *jenv, jclass jcls, jfloat jarg1) {
  jlong jresult = 0 ;
  float arg1 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  result = (float *)copy_floatp(arg1);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_delete_1floatp(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  float *arg1 = (float *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(float **)&jarg1; 
  delete_floatp(arg1);
}


SWIGEXPORT void JNICALL Java_flann_java_1flannJNI_floatp_1assign(JNIEnv *jenv, jclass jcls, jlong jarg1, jfloat jarg2) {
  float *arg1 = (float *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(float **)&jarg1; 
  arg2 = (float)jarg2; 
  floatp_assign(arg1,arg2);
}


SWIGEXPORT jfloat JNICALL Java_flann_java_1flannJNI_floatp_1value(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jfloat jresult = 0 ;
  float *arg1 = (float *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(float **)&jarg1; 
  result = (float)floatp_value(arg1);
  jresult = (jfloat)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

